### ISSUE TITLE
Support for Lightning Address

### ISSUE THREAD

**Issue by andrerfneves** [apotdevin/NextPay#4]
Hey @apotdevin I know you showed us on Telegram support for receiving to your personal address through NextPay, but was wondering if this is built on this package as well? Cheers!

**Comment by apotdevin** [comment]
Hey! Yes, correct. The latest master is what is deployed at nextpay.apotdevin.com

**Comment by apotdevin** [comment]
@andrerfneves just realized I closed this yesterday 😅 Let me know if theres anything else I can help you with!
