### ISSUE TITLE
Add a Deploy to Vercel button

### ISSUE THREAD

**Issue by futurepaul** [apotdevin/NextPay#7]
I just discovered this repo after building something very similar myself: https://github.com/futurepaul/addressless

A nice addition to NextPay would be a real Vercel deploy button, which can include all the necessary environment variables in its url so the user is guided through what they need to fill in. Documentation here: https://vercel.com/docs/deploy-button

If you check out my readme you can try out the deploy button and see how it works.

I'll probably close down my repo unless I find some good differentiation between what we're doing :)

**Comment by apotdevin** [comment]
Hey! Thanks for opening the feature request! This is a great idea 💯 

Seems like we had similar ideas! 💪

**Comment by futurepaul** [comment]
this button seems to be working, deployed here https://my-nextpay.vercel.app

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fapotdevin%2FNextPay&env=NAME,MAX,MIN,LND_MACAROON,LND_URL&envDescription=It's%20recommended%20that%20you%20use%20a%20macaroon%20that%20only%20has%20creating%20invoice%20permissions.%20The%20environment%20variables%20are%20never%20exposed%20to%20the%20public%20but%20better%20be%20safe%20than%20sorry.&envLink=https%3A%2F%2Fgithub.com%2Fapotdevin%2FNextPay%23environment-variables&demo-title=NextPay&demo-description=Your%20very%20own%20LNURL-Pay%20server%20built%20on%20NextJS.&demo-url=https%3A%2F%2Fnextpay.apotdevin.com&demo-image=https%3A%2F%2Fuser-images.githubusercontent.com%2F543668%2F143167362-71fa1247-c104-414a-a8aa-c244598592cd.png)

I'll create a PR

(image here because I'm using github as an image host)

<img width="991" alt="Screen Shot 2021-11-23 at 9 15 12 PM" src="https://user-images.githubusercontent.com/543668/143167362-71fa1247-c104-414a-a8aa-c244598592cd.png">
